language: cpp
git:
 submodules: false
compiler: 
 - gcc
 - clang
install:
 - sudo apt-add-repository -y ppa:ubuntu-sdk-team/ppa
 - sudo add-apt-repository --yes ppa:ubuntu-toolchain-r/test
 - if [ "$CXX" = "clang++" ]; then sudo add-apt-repository --yes ppa:h-rayflood/llvm; fi
 - sudo apt-get update -qq
 - sudo apt-get install libglew-dev
 - sudo apt-get install libglm-dev
 - if [ "$CXX" = "g++" ]; then sudo apt-get install -qq g++-4.8; fi
 - if [ "$CXX" = "clang++" ]; then sudo apt-get -qq install libstdc++-4.8-dev; fi
 - sudo apt-get install xorg-dev
 - sudo apt-get install cmake
 - git clone https://github.com/glfw/glfw.git
 - cd glfw
 - git checkout latest
 - sudo cmake .
 - sudo make && sudo make install
 - cd ..
 - if [ "$CXX" = "g++" ]; then export CXX="g++-4.8" LD="g++-4.8"; fi
 - if [ "$CXX" = "clang++" ]; then export LD="clang++"; fi
script: make
notifications:
  email: false
