language: cpp
compiler: 
 - gcc
 - clang
before-install: 
 - sudo apt-get update
install:
 - sudo apt-get install libglew-dev
 - sudo apt-get install libglm-dev
 - if [ "$CXX" = "g++" ]; then sudo add-apt-repository ppa:ubuntu-toolchain-r/test -y; fi
 - if [ "$CXX" = "g++" ]; then sudo apt-get update -qq; fi
 - if [ "$CXX" = "g++" ]; then sudo apt-get install -qq g++-4.8; fi
 - if [ "$CXX" = "g++" ]; then export CXX="g++-4.8" CC="gcc-4.8" LD="g++-4.8"; fi
 - sudo apt-get install xorg-dev
 - git clone https://github.com/glfw/glfw.git
 - cd glfw
 - sudo cmake .
 - sudo make && sudo make install
 - cd ..
script: make
notifications:
  email: false
