sudo: false
language: cpp
git:
 submodules: false
compiler:
 - gcc
 - clang
addons:
 apt:
  sources:
   - ppa:george-edison55-precise-backports
   - ppa:ubuntu-toolchain-r/test
  packages:
   - libglew-dev
   - libglfw3-dev
   - libglm-dev
   - libfreetype6-dev
   - g++-4.8
   - libstdc++-4.8-dev
install:
 - if [ "$CXX" = "g++" ]; then export CXX="g++-4.8" LD="g++-4.8"; fi
 - if [ "$CXX" = "clang++" ]; then export LD="clang++"; fi
script: make debug
notifications:
 email: false
