language: cpp
compiler: gcc
before-install: sudo apt-get update
install:
 - sudo apt-get install libglew-dev
 - sudo apt-get install libglfw-dev
 - sudo apt-get install libglm-dev
 - sudo apt-get install codeblocks
script: codeblocks OpenStrategia.cbp
