sudo: false
language: cpp
git:
	submodules: false
compiler:
	- gcc
	- clang
addons:
 apt:
  sources:
   - ppa:smspillaz/cmake-2.8.12
   - ppa:ubuntu-toolchain-r/test
  packages:
   - libglew-dev
   - libglm-dev
   - xorg-dev
   - cmake
   - libfreetype6-dev
   - g++-4.8
   - libstdc++-4.8-dev
install:
 - git clone https://github.com/glfw/glfw.git
 - cd glfw
 - git checkout latest
 - cmake .
 - make && make install
 - cd ..
 - if [ "$CXX" = "g++" ]; then export CXX="g++-4.8" LD="g++-4.8"; fi
 - if [ "$CXX" = "clang++" ]; then export LD="clang++"; fi
script: make debug
notifications:
 email: false
